bakery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, edit_product, delete_product, add_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>

  <footer>
    {% block footer %} {% endblock footer %}
  </footer>

</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>

  <footer>
    {% block footer %} {% endblock footer %}
  </footer>

</html>

templates/navbar.html
<!-- Tailwind CSS Navigation Bar -->
<nav class="bg-green-700 shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center h-16">
      <div class="hidden md:flex items-center justify-between w-full">
        {% if user.is_authenticated %}
        <div class="flex items-center space-x-10">
          <h1 class="text-2xl font-bold text-center text-white">Janssen's Bakery</h1>
          <a href="{% url 'main:show_main' %}" class="text-white font-bold">Home</a>
          <a href="{% url 'main:show_main' %}" class="text-white font-bold">Products</a>
          <a href="#" class="text-white font-bold">Categories</a>
          <a href="#" class="text-white font-bold">Cart</a>
        </div>
        <div class="flex items-center space-x-5">
          <span class="text-white mr-4 font-bold">Hello, {{ user.username }}!</span>
          <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300 border-2 border-black">
            Log Out
          </a>
        </div>
        {% else %}
        <h1 class="text-2xl font-bold text-center text-white">Janssen's Bakery</h1>
        <div class="flex items-center space-x-10">
          <a href="{% url 'main:login' %}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 border-2 border-black">
            Log In
          </a>
          <a href="{% url 'main:register' %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300 border-2 border-black">
            Register
          </a>
        </div>
        {% endif %}
      </div>
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- Mobile version -->
  <div class="mobile-menu hidden md:hidden px-4 w-full">
    <div class="pt-2 pb-3 space-y-1 mx-auto">
      {% if user.is_authenticated %}
        <a href="{% url 'main:show_main' %}" class="block text-white font-bold py-2">Home</a>
        <a href="{% url 'main:show_main' %}" class="block text-white font-bold py-2">Products</a>
        <a href="#" class="block text-white font-bold py-2">Categories</a>
        <a href="#" class="block text-white font-bold py-2">Cart</a>
        <span class="block text-white mr-4 font-bold py-2">Hello, {{ user.username }}!<br><br></span>
        <a href="{% url 'main:logout' %}" class="block bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Logout
        </a>
      {% else %}
        <a href="{% url 'main:login' %}" class="block bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
          Login
        </a>
        <a href="{% url 'main:register' %}" class="block bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Register
        </a>
      {% endif %}
    </div>
  </div>
  <script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");
    btn.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  </script>
</nav>

templates/navbar2.html
<!-- Tailwind CSS Navigation Bar -->
<nav class="bg-green-700 shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center h-16">
      <div class="hidden md:flex items-center justify-between w-full">
        {% if user.is_authenticated %}
        <div class="flex items-center space-x-10">
          <h1 class="text-2xl font-bold text-center text-white">Janssen's Bakery</h1>
          <a href="{% url 'main:show_main' %}" class="text-white font-bold">Home</a>
          <a href="{% url 'main:show_main' %}" class="text-white font-bold">Products</a>
          <a href="" class="text-white font-bold">Categories</a>
          <a href="" class="text-white font-bold">Cart</a>
        </div>
        <div class="flex items-center space-x-5">
          <span class="text-white mr-4 font-bold">Hello, {{ user.username }}!</span>
          <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Log Out
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
            Log In
          </a>
          <a href="{% url 'main:register' %}" class="text-center bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
        </div>
      </div>
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- Mobile menu -->
  <div class="mobile-menu hidden md:hidden  px-4 w-full md:max-w-full">
    <div class="pt-2 pb-3 space-y-1 mx-auto">
      {% if user.is_authenticated %}
        <a href="{% url 'main:show_main' %}" class="block text-white font-bold py-2">Home</a>
        <a href="{% url 'main:show_main' %}" class="block text-white font-bold py-2">Products</a>
        <a href="#" class="block text-white font-bold py-2">Categories</a>
        <a href="#" class="block text-white font-bold py-2">Cart</a>
        <span class="block text-white px-3 py-2">Hello, {{ user.username }}!</span>
        <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Logout
        </a>
      {% else %}
        <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
          Login
        </a>
        <a href="{% url 'main:register' %}" class="block text-center bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Register
        </a>
      {% endif %}
    </div>
  </div>
  <script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");
    btn.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  </script>
</nav>