bakery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, edit_product, delete_product, add_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    category = models.CharField(max_length=255)
    quantity = models.IntegerField(default=0)

    @property
    def __str__(self):
        return self.name
    @property
    def is_in_stock(self):
        return self.quantity > 0

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "category", "quantity"]

    def clean_name(self):
        return strip_tags(self.cleaned_data["name"])
    
    def clean_category(self):
        return strip_tags(self.cleaned_data["category"])
    
    def clean_description(self):
        return strip_tags(self.cleaned_data["description"])

main/views.py
from django.shortcuts import render, redirect
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json
from django.http import JsonResponse

@login_required(login_url='/login')
def show_main(request):
    context = {
        'title' : "Janssen's Bakery",
        'npm' : '2306152102',
        'name': request.user.username,
        'class': 'PBP D',
        'last_login': request.user.last_login if request.user.last_login else None,
    }
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_main')
    context = {'form' : form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your new account has been created.')
            return redirect('main:login')
    context = {'form' : form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Incorrect Username/Password. Try Again.")
    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    form = ProductForm(request.POST or None, instance = Product.objects.get(pk=id))
    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    Product.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    description = strip_tags(request.POST.get("description"))
    quantity = request.POST.get("quantity")
    category = strip_tags(request.POST.get("category"))
    user = request.user
    new_product = Product(name=name, price=price, description=description, quantity=quantity, category=category, user=user)
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"],
            quantity=int(data["quantity"]),
            category=data["category"],
        )
        new_product.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_info.html
<div class="bg-green-700 overflow-hidden border-2 border-black">
  <div class="p-3 animate-shine">
    <h5 class="text-lg font-bold text-white">{{ title }}</h5>
    <p class="text-white">{{ value }}</p>
  </div>
</div>

main/templates/card_product.html
<div class="relative">
  <div class="relative mt-5 bg-gray-50 shadow-sm mb-4 border-2 border-black">
    <div class="text-white p-3 animate-shine" style="background-color: #198754;">
      <h3 class="font-bold text-xl mb-2">{{ product.name }}</h3>
      <p>Price (IDR): {{ product.price }}</p>
    </div>
    <div class="p-3">
      <p class="font-semibold text-lg mb-2">Category</p> 
        <span>{{ product.category }}</span>
      <p class="font-semibold text-lg mb-2">Description</p> 
        <span>{{ product.description }}</span>
      <div class="mt-3">
        <p class="font-semibold text-lg mb-2">Quantity</p> 
        <span>{% if product.quantity == 0 %}
            OUT OF STOCK
          {% else %}
            {{ product.quantity }}
          {% endif %}</span>      
      </div>
    </div>
  </div>
  <div class="absolute bottom-0 right-0 flex mr-2 py-2">
    <a href="{% url 'main:edit_product' product.pk %}" class="btn-warning bg-purple-300 text-white rounded-full p-2 border-2 border-black mr-2">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
      </svg>
    </a>
    <a href="{% url 'main:delete_product' product.pk %}" class="bg-red-200 text-white rounded-full p-2 border-2 border-black shadow-sm">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>
    </a>
  </div>
</div>

main/templates/create_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Create Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen" style="background-image: url('{% static 'pics/bakeryBG.jpg' %}'); background-repeat: repeat; background-size: contain;">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Create Bakery Product</h1>
    <div class="bg-gray-100 rounded-lg p-6 form-style border-2 border-black">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-black">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-green-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-green-600 transition duration-300 ease-in-out w-full">
            Create Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Product</title>
{% endblock meta %} 

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen" style="background-image: url('{% static 'pics/bakeryBG.jpg' %}'); background-repeat: repeat; background-size: contain;">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Edit Bakery Product</h1>
    <div class="bg-gray-100 rounded-lg p-6 form-style border-2 border-black">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-black">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-black">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-500">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
              <button type="submit" class="bg-green-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-green-600 transition duration-300 ease-in-out w-full">
                  Edit Product
              </button>
          </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="min-h-screen flex items-center justify-center w-screen py-12 px-4 sm:px-6 lg:px-8" style="background-image: url('{% static 'pics/bakeryBG.jpg' %}'); background-repeat: repeat; background-size: contain;">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-black text-3xl font-extrabold text-black">
        Welcome to Janssen's Bakery!
        <br><br>
        Log In To Your Account Here!
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Log In
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-300 text-green-600 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-300 text-red-600 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-300 text-blue-600 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4 rounded-lg bg-black p-2">
      <p class="text-sm text-white">
        No Account? Not To Worry,
        <a href="{% url 'main:register' %}" class="font-medium text-green-500 hover:text-green-500">
          Register Here!
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
<title>Janssen's Bakery</title>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="container-fluid px-6 py-20 min-h-screen flex flex-col" style="background-image: url('{% static 'pics/bakeryBG.jpg' %}'); background-repeat: repeat; background-size: contain;">
  <div class="mb-4 py-1">
      {% include "card_info.html" with title='NPM' value=npm %}
      {% include "card_info.html" with title='Name' value=name %}
      {% include "card_info.html" with title='Class' value=class %}
  </div>
  <h6 class="font-bold text-left">Last Login Session: {{ last_login }}</h6>
  <div class="flex justify-end items-center py-4">
    <a href="{% url 'main:create_product' %}" class="btn bg-green-600 hover:bg-green-700 font-bold py-2 px-4 border-2 border-black text-center mr-3" style="color:white">
      Add New Product
    </a>
    <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-green-600 hover:bg-green-700 border-2 border-black text-white font-bold py-2 px-4 duration-300" onclick="showModal();">
      Add New Product by AJAX
    </button>
  </div>
  <div id="product_cards"></div>
  <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-gray-50 border-black border-2 shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">

      <div class="flex items-center justify-between p-4 border-b bg-green-700">
        <h3 class="text-xl font-semibold text-white">Add New Product</h3>
        <button type="button" class="bg-transparent hover:bg-green-600 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
          <svg aria-hidden="true" class="w-5 h-5" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>

      <div class="px-6 form-style">
        <form id="productForm">
          <div class="mt-4 mb-3">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-700" placeholder="Enter Product Name" required>
          </div>
          <div class="mb-3">
            <label for="price" class="block text-sm font-medium text-gray-700">Price (IDR)</label>
            <input type="number" id="price" name="price" min="0" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-700" placeholder="How Much Is The Price?" required>
          </div>
          <div class="mb-3">
            <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea id="description" name="description" rows="4" class="mt-1 block w-full h-25 border-2 border-black rounded-md p-2 hover:border-green-700" placeholder="Describe The Product" required></textarea>
          </div>
          <div class="mb-3">
            <label for="category" class="block text-sm font-medium text-gray-700">Category</label>
            <input type="text" id="category" name="category" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-700" placeholder="State Product Category" required>
          </div>
          <div class="mb-3">
            <label for="quantity" class="block text-sm font-medium text-gray-700">Quantity</label>
            <input type="number" id="quantity" name="quantity" min="0" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-700" placeholder="How Much Is In Stock?" required>
          </div>
        </form>
      </div>

      <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-4 border-t border-gray-200 justify-center md:justify-end">
        <button type="button" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4" id="cancelButton">Cancel</button>
        <button type="submit" id="submitProduct" form="productForm" class="bg-green-700 hover:bg-green-800 text-white font-bold py-2 px-4">Create Product</button>
      </div>
    </div>
  </div>
</div>
<script>
  async function getProducts(){
    return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }
  async function refreshProducts() {
    document.getElementById("product_cards").innerHTML = "";
    document.getElementById("product_cards").className = "";
    const products = await getProducts();
    let htmlString = "";
    let classNameString = "";
    if (products.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `<div class="flex flex-col items-center justify-center" style="min-height: 24rem;">
            <img src="{% static 'pics/no.png' %}" alt="Nothing Here" class="w-30 h-30 mt-4 mb-4 py-2">
            <h4 class="mb-0 text-center font-bold">Apologies, There Are No Products Available At The Moment</h1>
          </div>`;
    } else {
        classNameString = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full"
        products.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const description = DOMPurify.sanitize(item.fields.description);
            const category = DOMPurify.sanitize(item.fields.category);
            htmlString += `<div class="relative break-inside-avoid animate-shine">
                <div class="relative bg-black shadow-sm mt-4 border-2 border-black break-inside-avoid flex flex-col duration-300">
                    <div class="text-white p-3 animate-shine" style="background-color: #198754;">
                      <h3 class="font-bold text-xl mb-2">${name}</h3>
                      <p>Price (IDR): ${item.fields.price}</p>
                    </div>
                    <div class="p-3 animate-shine text-white">
                      <p class="font-semibold text-lg mb-2">Description</p> 
                      <span> ${description}</span>
                      <p class="font-semibold text-lg mb-2 mt-4">Category</p> 
                      <span> ${category}</span>
                      <div class="flex items-center justify-between mt-4">
                        <div>
                            <p class="text-lg font-semibold mb-2">Quantity</p>
                            <span>${item.fields.quantity > 0 ? item.fields.quantity : 'OUT OF STOCK'}</span>
                        </div>
                        <div class="flex mt-4">
                            <a href="/edit/${item.pk}" class="btn-warning bg-purple-300 text-white rounded-full p-2 border-2 border-black mr-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20">
                                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                </svg>
                            </a>
                            <a href="/delete/${item.pk}" class="bg-red-200 text-white rounded-full p-2 border-2 border-black shadow-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                                </svg>
                            </a>
                        </div>
                      </div>
                    </div>
                </div>
            </div>`;});
    }
    document.getElementById("product_cards").className = classNameString;
    document.getElementById("product_cards").innerHTML = htmlString;
  }
  refreshProducts();

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-99');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-99');

      setTimeout(() => { modal.classList.add('hidden'); }, 150); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  function addProduct() {
    fetch("{% url 'main:add_product_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#productForm')),
    }).then(response => refreshProducts())
    document.getElementById("productForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();
    return false;
  }

  fetch('http://something.com').then(response => {console.log(response.status)});

  document.getElementById("productForm").addEventListener("submit", (e) => { e.preventDefault(); addProduct(); })

</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8" style="background-image: url('{% static 'pics/bakeryBG.jpg' %}'); background-repeat: repeat; background-size: contain;">
  <div class="max-w-md w-full space-y-8 form-style">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-black">
        Make Your Account Here!
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        {% for field in form %}
          <div class="{% if not forloop.first %}mt-4{% endif %}">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-black">
              {{ field.label }}
            </label>
            <div class="relative">
              {{ field }}
              <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                {% if field.errors %}
                  <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                {% endif %}
              </div>
            </div>
            {% if field.errors %}
              {% for error in field.errors %}
                <p class="mt-1 text-sm text-red-500">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
          Register
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <span class="block sm:inline">{{ message }}</span>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4 rounded-lg bg-black p-2">
      <p class="text-sm text-white">
        Oh, You Have An Account? Well Then,
        <a href="{% url 'main:login' %}" class="font-medium text-green-600 hover:text-green-700">
          Log In Here!
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}